version: '3.0'
services:
  database:
    image: amsterdam/postgres11
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: bag
      POSTGRES_DB: bag

  postcode:
    build: .
    links:
      - database
    ports:
      - "8080"
    environment:
      DATABASE_PORT_5432_TCP_ADDR: database
      DATABASE_PORT_5432_TCP_PORT: 5432
      DATABASE_NAME: bag
      DATABASE_PASSWORD: insecure
      UWSGI_HTTP: ":8080"
      UWSGI_MODULE: "server"
      UWSGI_CALLABLE: "app"
      UWSGI_MASTER: 1

