database:
  image: admin.datapunt.amsterdam.nl:5000/atlas/postgres:latest
  ports:
    - "5432"
  environment:
    POSTGRES_PASSWORD: insecure
    POSTGRES_USER: postgres
    POSTGRES_DB: atlas

postcode:
  build: .
  links:
    - database:database
  ports:
    - "8080"
